services:
  sbt:
    image: sbtscala/scala-sbt:eclipse-temurin-jammy-11.0.22_7_1.9.9_3.4.0
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - lila-network

  primary:
    image: mongo:5.0.26-focal
    command: mongod --bind_ip_all --replSet rs0
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'primary:27017',priority:1},{_id:1,host:'secondary0:27017',priority:0.5},{_id:2,host:'secondary1:27017',priority:0.5}]}) }" | mongosh --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    networks:
      - lila-network

  secondary0:
    image: mongo:5.0.26-focal
    command: mongod --bind_ip_all --replSet rs0
    networks:
      - lila-network

  secondary1:
    image: mongo:5.0.26-focal
    command: mongod --bind_ip_all --replSet rs0
    networks:
      - lila-network

  mongo_express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH=false
      - ME_CONFIG_MONGODB_SERVER=primary
    networks:
      - lila-network

networks:
  lila-network:
    driver: bridge
